### ISSUE TITLE
Extend Python development documentation on how to retrieve keys and values

### ISSUE THREAD

**Issue by pombredanne** [libyal/libregf#13]
It would help to get started to have some minimal doc for the Python bindings.

**Comment by joachimmetz** [comment]
And this page (https://github.com/libyal/libregf/wiki/Python-development) does not suffice?

**Comment by pombredanne** [comment]
It does... I had not seen it!
I guess it could have a an simple example showing how you read a path/key and get the value(s) out.
(Side note:  I want to say that your libyal libraries really rock and are rather unique! I am looking into them for Windows package/installed program detection for https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/win_reg.py and https://github.com/nexB/scancode.io/pull/181 )

**Comment by joachimmetz** [comment]
so libregf/pyregf is mainly intended to deal with the REGF format, if you're looking for something that tries to mimic Windows Registry closer have a look at https://github.com/log2timeline/dfwinreg 

If you need examples of how dfWinReg can be used https://github.com/libyal/winreg-kb, otherwise https://github.com/log2timeline/plaso/blob/main/plaso/parsers/winreg_parser.py

**Comment by joachimmetz** [comment]
Added some information about getting keys https://github.com/libyal/libregf/wiki/Python-development

**Comment by pombredanne** [comment]
Thank you ++... that and the pointers above are more than good enough. Closing then.
